### ISSUE TITLE
Unique<T> is unsound

### ISSUE THREAD

**Issue by CryZe** [DoumanAsh/smart-ptr#1]
If I pass garbage to Unique::new[_default] and then call .as_mut() I get a mutable reference to garbage. And additionally I can alias that too, as it takes &self as receiver (among other ways to alias it).

**Comment by DoumanAsh** [comment]
You need to be a bit more specific: what do you mean by garbage?

If you mean dangling or just pointer to non-existing memory then yes, it might be unsound.
But this is your fault, not `Unique<T>` unsoundness.
There is no way to verify that pointer is correct.

Which means that `Unique::as_mut` should be unsafe, but it is not because I use `Unique` correctly and too lazy to write `unsafe` just because someone might use it incorrectly

**Comment by DoumanAsh** [comment]
Do note that `Unique` should not control object creation as the intention is to manage raw pointer(which is likely to be passed from C FFI)

**Comment by CryZe** [comment]
Yeah the unsoundness revolves around .as_mut() not being unsafe when it should (among other methods, such as Deleter::delete(...)). Releasing a crate for other people to use without marking the unsafe APIs as unsafe is not great. In fact this should possibly even result in version 0.1 and 0.2 being yanked from crates.io with a security advisory on rustsec.

An alternative is to mark the constructors as unsafe and forbid passing garbage (with a clear definition of what is not considered garbage, i.e. the pointer needs to truly be non-aliased, unique, properly allocated with the Deleter's allocator, properly aligned, live long enough, ...).

**Comment by DoumanAsh** [comment]
Just to clarify how these two cases would be different:

```
let garbage = Unique:<u8, ()>:new(mem::transmute(1) u8, ()); //or any other way to get garbage ptr
```

```
let garbage: Unique<u8, ()> = mem::unitiniazlied()
```

**Comment by CryZe** [comment]
The second involves unsafe + UB outside of the Unique<T> API, the first one is entirely safe code and has UB from the inside of the API (you don't need that transmute, a pointer pointing to anything can be created in safe Rust).

```rust
let unique_string = Unique::<String, ()>::new(2345 as *mut String, ());
unique_string.as_mut().append_str("Whoops, segfault");
```

**Comment by DoumanAsh** [comment]
So unsound casts to pointer (which is safe) is ok.
But not in my case.
Ok, I'll think about it.

But for me it is non-issue, so low priority.

**Comment by CryZe** [comment]
Well there are other issues such as creating a totally valid Unique<T>, but then calling .as_mut() multiple times at the same time, which breaks Rust's most important guarantee that this should never be possible, which causes Undefined Behavior and thus probably broken code. So even with a valid Unique<T>, you can have all sorts of **security critical** issues with the API. While that may be fine for you, I'd at least mark this somewhere so potential users of the crate are aware of this (which is kind of the point of unsafe).

**Comment by DoumanAsh** [comment]
I switched to DerefMut for now, because it is not possible to make borrow checker to disallow multiple borrows via `as_mut()`.

The same applies to `DerefMut::deref_mut` but normally you do not call it manually

**Comment by DoumanAsh** [comment]
I checked various ways around NLL.
And as long as alias is actually used by your code, NLL will not let you perform two mutations via two distinguish aliases.
You still able to do something like:

```rust
let value = ptr.deref_mut();
*value.0 = true;
let value2 = ptr.deref_mut();
*value2.0 = true;
```

Which is safe.
But compiler will complain if you try to re-order mutations like that:

```rust
let value = ptr.deref_mut();
let value2 = ptr.deref_mut();
*value2.0 = true;
*value.0 = true;
```

Anyway, 0.3 should no longer be unsound, aside from Deleter that uses Rust's global allocator.
But there is nothing I can do about it
